Unsapa\IPWBundle\Entity\Exam:
    type: entity
    table: ipw_exam
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: '255'
            nullable: false
        exam_desc:
            type: text
            length: null
            nullable: true
        exam_date:
            type: datetime
            length: null
            nullable: true
        coef:
            type: float
            length: null
            nullable: true
        state:
            type: string
            length: 64
            nullable: false
    lifecycleCallbacks: {  }
    manyToOne:
      promo:
        targetEntity: Unsapa\IPWBundle\Entity\Promo
        nullable: false
      resp:
        targetEntity: Unsapa\IPWBundle\Entity\User
        nullable: false
