Unsapa\IPWBundle\Entity\Exam:
    type: entity
    table: ipw_exam
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: '255'
        exam_desc:
            type: text
            length: null
        exam_date:
            type: datetime
            length: null
        coef:
            type: float
            length: null
        state:
            type: string
            length: 64
    lifecycleCallbacks: {  }
    manyToOne:
      promo:
        nullable: false
        targetEntity: Unsapa\IPWBundle\Entity\Promo
    oneToOne:
      resp:
        targetEntity: Unsapa\IPWBundle\Entity\User
